/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Tarcísio
 */
public class JFSplash extends javax.swing.JFrame {

    /**
     * Creates new form JFSplash
     */
    public JFSplash() {
        initComponents();
      
        
// Inicio do código para Tela de Splash
        
new Thread(){

public void run (){

for (int i = 0; i < 101; i++) {

try {    
sleep (60);

jProgressBar1.setValue(i);
if (jProgressBar1.getValue()<=40 ){
jLabel1.setText("Carregando o banco de dados ...");
}
else if 
(jProgressBar1.getValue()<=70 ){
jLabel1.setText("Carregando as tabelas ...");
}
else{
jLabel1.setText("Inicializando o sistema ...");

}

} catch (InterruptedException ex) {
Logger.getLogger(JFSplash.class.getName()).log(Level.SEVERE, null, ex);
}
}
// Chamar a Tela de login e Ocultar a tela splash

new JFLogin().setVisible(true);
JFSplash.this.dispose();
}    




}.start();

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try {
            jProgressBar1 =(javax.swing.JProgressBar)java.beans.Beans.instantiate(getClass().getClassLoader(), "Visao.JFSplash_jProgressBar1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 174, 45));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 160, 337, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/icones telas/Tela_Splash.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 618, 320);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(420, 170, 150, 20);

        setSize(new java.awt.Dimension(618, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
